import { StyleSheet, Dimensions } from 'react-native';
import { theme } from './theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const HERO_CARD_WIDTH = SCREEN_WIDTH - 52;
export const HERO_CARD_HEIGHT = 368;

export const cHCardStyles = StyleSheet.create({
  card: {
    width: HERO_CARD_WIDTH,
    height: HERO_CARD_HEIGHT,
    overflow: 'hidden',
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1.5,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  cardActive: {
    borderColor: theme.colors.primary,
    backgroundColor: '#FAFBFF',
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  platformBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 100,
    borderWidth: 1,
  },
  platformText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  momentumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 149, 0, 0.10)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 100,
  },
  momentumText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF9500',
  },
  instructorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  instructorText: {
    fontSize: 12,
    color: theme.colors.text.placeholder,
    fontWeight: '500',
  },
  courseName: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.colors.text.primary,
    letterSpacing: -0.4,
    lineHeight: 26,
    marginBottom: 6,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginBottom: 8,
  },
  tagBadge: {
    backgroundColor: theme.colors.primary + '18',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  tagText: {
    fontSize: 10,
    color: theme.colors.primary,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginBottom: 14,
    opacity: 0.6,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  stat: {
    flex: 1,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.colors.text.primary,
    letterSpacing: -0.3,
  },
  statLabel: {
    fontSize: 10,
    color: theme.colors.text.placeholder,
    fontWeight: '500',
    marginTop: 1,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: theme.colors.border,
  },
  progressBarBg: {
    height: 4,
    backgroundColor: theme.colors.border,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 4,
  },
  classesText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: 2,
  },
  remainingText: {
    fontSize: 12,
    color: theme.colors.text.placeholder,
    fontWeight: '500',
  },
  knowledgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: theme.colors.primary + '08',
    borderRadius: 10,
    marginTop: 10,
  },
  knowledgeLabel: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    fontWeight: '500',
  },
  knowledgeValue: {
    fontSize: 14,
    fontWeight: '700',
  },
  continueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: theme.colors.primary + '10',
    borderRadius: 12,
  },
  continueText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
    flex: 1,
  },
  continueIcon: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  statsSimple: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 12,
  },
  statSimpleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  statSimpleText: {
    fontSize: 12,
    color: theme.colors.text.placeholder,
    fontWeight: '500',
  },
  urlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 16,
  },
  urlText: {
    fontSize: 11,
    color: theme.colors.text.placeholder,
    fontWeight: '500',
    flex: 1,
  },
  mainUrlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  mainUrlText: {
    fontSize: 12,
    color: theme.colors.primary,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  cardAllGlobal: {
    backgroundColor: theme.colors.card,
    borderColor: 'transparent',
  },
  cardActiveGlobal: {
    borderColor: theme.colors.primary,
    borderWidth: 1.5,
    backgroundColor: '#FAFBFF',
  },
  globalEcosystemRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
  },
  ecosystemItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ecosystemText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    fontWeight: '500',
  },
  recommendationSection: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: theme.colors.primary + '10',
    borderRadius: 12,
    marginTop: 4,
  },
  recommendationHeader: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.text.placeholder,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  recommendationSubject: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  recommendationDetail: {
    fontSize: 12,
    color: theme.colors.primary,
    fontWeight: '500',
    marginTop: 2,
  },
  recentActivitySection: {
    marginTop: 12,
  },
  recentActivityHeader: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.text.placeholder,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
  },
  activityDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 10,
  },
  activityName: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.text.primary,
    flex: 1,
  },
  activityTime: {
    fontSize: 11,
    color: theme.colors.text.placeholder,
    fontWeight: '500',
  },
  moreCount: {
    fontSize: 11,
    color: theme.colors.text.placeholder,
    fontWeight: '500',
    marginTop: 4,
    marginLeft: 16,
  },
  examBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginTop: 8,
  },
  examText: {
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  examCountdown: {
    fontSize: 12,
    fontWeight: '700',
  },
});
