import { StyleSheet, Platform } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const dashboardStyles = StyleSheet.create({
  syncIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary + '12',
    borderRadius: theme.borderRadius.full,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginBottom: 12,
    alignSelf: 'center',
  },
  syncIndicatorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.primary,
    marginRight: 8,
  },
  syncIndicatorText: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.primary,
    fontWeight: '500',
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.lg,
    paddingBottom: 50,
  },
  header: { ...globalStyles.standardHeader, paddingHorizontal: 0, paddingVertical: 12, marginBottom: theme.spacing.lg },
  greetingText: globalStyles.screenTitle,
  greetingSubtext: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    fontWeight: '400',
    marginTop: 6,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: theme.colors.border,
  },
  section: {
    marginBottom: 28,
  },
  sectionTitle: {
    fontSize: theme.typography.sizes.lg,
    fontWeight: '700',
    color: theme.colors.text.primary,
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  subjectsRow: {
    gap: 12,
    paddingVertical: 8,
  },
  subjectsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  subjectsAddBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subjectsCarousel: {
    paddingVertical: 4,
    paddingRight: 4,
  },
  subjectTile: {
    width: 160,
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...globalStyles.shadow,
  },
  subjectBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    zIndex: 2,
  },
  subjectTileName: {
    fontSize: theme.typography.sizes.md, // Close to 15
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  subjectTileMeta: {
    fontSize: theme.typography.sizes.sm, // Close to 12
    color: theme.colors.text.secondary,
    marginTop: 4,
    fontWeight: '400',
  },
  subjectTileStats: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    marginTop: 8,
    fontWeight: '500',
  },
  emptySubjectsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.md,
  },
  emptySubjectsText: {
    color: theme.colors.text.secondary,
    fontSize: theme.typography.sizes.sm,
  },
  emptyCourseCard: {
    backgroundColor: theme.colors.primary + '10',
    borderWidth: 1,
    borderColor: theme.colors.primary + '40',
    borderRadius: theme.borderRadius.lg,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    gap: 12,
  },
  emptyCourseTitle: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  emptyCourseSubtext: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 10,
  },
  emptyCourseBtn: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: theme.borderRadius.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  emptyCourseBtnText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: theme.typography.sizes.sm,
  },
  subjectCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
  },
  subjectImage: {
    width: '100%',
    height: '100%',
  },
  quickAddCard: {
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.lg,
    padding: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  quickAddTitle: {
    fontSize: theme.typography.sizes.lg,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  quickAddDesc: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.text.secondary,
    marginBottom: 14,
    fontWeight: '400',
  },
  quickAddBtn: {
    backgroundColor: theme.colors.white,
    paddingVertical: 11,
    borderRadius: theme.borderRadius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  quickAddBtnText: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  nextClassCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
    padding: 14,
    borderRadius: theme.borderRadius.lg,
    ...globalStyles.shadow,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
  },
  nextClassInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  nextClassBadge: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: theme.colors.primary + '15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextClassTitle: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  nextClassRoom: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    marginTop: 3,
    fontWeight: '400',
  },
  openBtn: {
    backgroundColor: theme.colors.inputBackground,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  openBtnText: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  grid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg,
    padding: 14,
    ...globalStyles.shadow,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    fontWeight: '500',
    flex: 1,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardValue: {
    fontSize: theme.typography.sizes.xxl,
    fontWeight: '700',
    color: theme.colors.text.primary,
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  cardSubtext: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    fontWeight: '400',
  },
  actionsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  actionItem: {
    width: 72,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: theme.spacing.xs,
  },
  actionCircle: {
    width: 56,
    height: 56,
    borderRadius: theme.borderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
  },
  actionText: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '500',
    color: theme.colors.text.primary,
    textAlign: 'center',
    lineHeight: 15,
  },
  allChip: {
    backgroundColor: theme.colors.text.secondary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: theme.borderRadius.full,
  },
  allChipText: {
    color: theme.colors.white,
    fontWeight: '600',
    fontSize: 12,
  },
  perfContainer: {
    gap: 10,
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'flex-end',
  },
  sheetContent: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: theme.spacing.lg,
    paddingBottom: Platform.OS === 'ios' ? 44 : 52,
    maxHeight: '85%',
    ...globalStyles.shadow,
  },
  sheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.border,
    alignSelf: 'center',
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: theme.typography.sizes.xl,
    fontWeight: '700',
    color: theme.colors.text.primary,
    letterSpacing: -0.5,
  },
  sheetSubtitle: {
    marginTop: 4,
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    marginBottom: 14,
  },
  sheetLabel: {
    marginTop: 14,
    marginBottom: 8,
    fontSize: theme.typography.sizes.md,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  sheetInput: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: theme.colors.text.primary,
    fontSize: theme.typography.sizes.md,
  },
  optionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  colorOption: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: theme.colors.border,
  },
  colorOptionSelected: {
    borderWidth: 2,
    borderColor: theme.colors.primary,
  },
  iconOption: {
    width: 40,
    height: 40,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.inputBackground,
  },
  iconOptionSelected: {
    borderColor: theme.colors.primary,
    borderWidth: 2,
  },
  sheetActions: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  sheetCancelBtn: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
  },
  sheetCancelText: {
    color: theme.colors.text.secondary,
    fontWeight: '600',
    fontSize: 15,
  },
  sheetSaveBtn: {
    borderRadius: theme.borderRadius.md,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
  },
  sheetSaveText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  perfRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
    padding: 12,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  perfRowYou: {
    backgroundColor: theme.colors.background,
    ...globalStyles.shadow,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  perfRank: {
    width: 40,
    fontWeight: '600',
    color: theme.colors.text.secondary,
  },
  perfUser: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  perfName: {
    fontSize: 14,
    color: theme.colors.text.primary,
    fontWeight: '500',
  },
  perfGpa: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '600',
    color: theme.colors.text.secondary,
  },
  quickAddMenuContainer: {
    marginTop: 16,
    gap: 12,
  },
  quickAddMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    padding: 14,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  quickAddMenuIcon: {
    width: 42,
    height: 42,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  quickAddMenuInfo: {
    flex: 1,
  },
  quickAddMenuText: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  quickAddMenuSubtext: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    marginTop: 2,
    fontWeight: '400',
  },
  quickAddMenuChevron: {
    opacity: 0.3,
  },
  // DROPDOWN / PICKER REPLACEMENT
  dropdownSelector: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
  },
  dropdownSelectorText: {
    fontSize: theme.typography.sizes.md,
    color: theme.colors.text.primary,
  },
  dropdownPlaceholder: {
    color: theme.colors.text.placeholder,
  },
  // TOAST STYLE (Simple)
  toastContainer: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: theme.colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: theme.borderRadius.full,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...globalStyles.shadow,
    zIndex: 999,
  },
  toastText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: theme.typography.sizes.sm,
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 24,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    ...globalStyles.shadow,
    elevation: 8,
    zIndex: 900,
  },
  gridContainer: {
    height: 460,
    backgroundColor: theme.colors.background,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 10,
  },
  gridHeader: {
    flexDirection: 'row',
    backgroundColor: theme.colors.inputBackground,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  hourColHeader: {
    width: 50,
  },
  dayColHeader: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.border + '40',
  },
  dayHeaderText: {
    fontSize: theme.typography.sizes.xs,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
  },
  scheduleHintText: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    marginBottom: 10,
  },
  gridRow: {
    flexDirection: 'row',
    height: 44,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border + '40',
  },
  hourCol: {
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.inputBackground + '50',
  },
  hourText: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
  gridCell: {
    flex: 1,
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.border + '20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  slotIndicator: {
    width: '80%',
    height: '80%',
    borderRadius: 4,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  // CAMERA STYLES
  cameraContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
  },
  cameraControls: {
    position: 'absolute',
    bottom: 50,
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  captureBtn: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 6,
    borderColor: 'rgba(255,255,255,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureBtnInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFF',
  },
  cameraCloseBtn: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // SNOOZE BUTTON
  snoozeBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  snoozeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
});
