import { StyleSheet, Platform } from 'react-native';
import { theme } from './theme';

export const globalStyles = {
  shadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  }
};

export const documentScannerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  guideScreen: {
    flex: 1,
    paddingTop: 60,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    marginBottom: 40,
  },
  closeBtn: {
    padding: 8,
    marginLeft: -8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  headerSpacer: {
    width: 28,
  },
  guideContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  levelIndicator: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 4,
    borderColor: theme.colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    backgroundColor: theme.colors.inputBackground,
  },
  levelIndicatorActive: {
    borderColor: '#4ade80',
    backgroundColor: '#4ade8020',
  },
  levelBubble: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.border,
  },
  levelBubbleActive: {
    backgroundColor: '#4ade80',
    transform: [{ scale: 1.2 }],
  },
  guideTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: theme.colors.text.primary,
    textAlign: 'center',
    marginBottom: 12,
  },
  guideSubtitle: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  guideFooter: {
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 44 : 52,
  },
  launchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    borderRadius: 30,
    gap: 12,
  },
  launchBtnActive: {
    backgroundColor: theme.colors.primary,
  },
  launchBtnInactive: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  launchBtnText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  launchBtnTextInactive: {
    color: theme.colors.text.secondary,
  },
  savingContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 20,
    paddingTop: 52,
    paddingBottom: 0,
  },
  savingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  savingHeaderTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.colors.text.primary,
    flex: 1,
    textAlign: 'center',
  },
  previewCard: {
    flex: 0.5,
    backgroundColor: 'white',
    borderRadius: 16,
    overflow: 'hidden',
    marginTop: 20,
    ...globalStyles.shadow,
  },
  previewImage: {
    flex: 1,
  },
  scanEffect: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  stepTitle: {
    color: theme.colors.text.primary,
    fontSize: 24,
    fontWeight: '700',
    marginTop: 24,
  },
  sectionBlock: {
    marginBottom: 12,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  modeSelector: {
    marginTop: 16,
  },
  modeLabel: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    marginBottom: 8,
  },
  modeBadges: {
    flexDirection: 'row',
    gap: 8,
  },
  modeBadge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  modeBadgeActive: {
    backgroundColor: theme.colors.primary + '18',
    borderColor: theme.colors.primary,
  },
  modeBadgeText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
  modeBadgeTextActive: {
    fontSize: 12,
    color: theme.colors.primary,
    fontWeight: '700',
  },
  subjectBadgeOverride: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  subjectScrollContainer: {
    paddingVertical: 4,
    gap: 8,
  },
  subjectItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: theme.colors.inputBackground,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minWidth: 110,
  },
  subjectName: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.text.primary,
    flex: 1,
  },
  saveActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 'auto',
    paddingBottom: Platform.OS === 'ios' ? 44 : 52,
    paddingTop: 12,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 52,
    borderRadius: 26,
    gap: 7,
  },
  actionBtnFlashcard: {
    backgroundColor: theme.colors.primary + '15',
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
  },
  actionBtnSave: {
    backgroundColor: theme.colors.primary,
  },
  actionBtnText: {
    fontSize: 14,
    fontWeight: '700',
  },
  primaryBtn: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtnText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  primaryBtnDisabled: {
    opacity: 0.4,
  },
  secondaryBtn: {
    flex: 1,
    backgroundColor: theme.colors.inputBackground,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  secondaryBtnText: {
    color: theme.colors.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  ocrIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#C5A05918',
    borderWidth: 1.5,
    borderColor: '#C5A059',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderText: {
    marginTop: 16,
    fontSize: 15,
    color: 'white',
    fontWeight: '600',
  },
  ocrOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '60%',
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    zIndex: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  ocrHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  ocrTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  ocrScroll: {
    flex: 1,
    backgroundColor: theme.colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  ocrText: {
    fontSize: 15,
    lineHeight: 24,
    color: theme.colors.text.primary,
  },
  ocrCopyButton: {
    flexDirection: 'row',
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ocrCopyText: {
    color: theme.colors.white,
    fontSize: 16,
    fontWeight: '600',
  }
});
