import { StyleSheet, Platform } from 'react-native';
import { theme } from './theme';

export const flashcardsScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.card,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: theme.spacing.lg,
    paddingRight: theme.spacing.md,
    paddingTop: 14,
    paddingBottom: 4,
    backgroundColor: theme.colors.card,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.colors.text.primary,
    flex: 1,
    textAlign: 'left',
  },
  backBtn: {
    padding: 4,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  searchBtnActive: {
    backgroundColor: `${theme.colors.primary}12`,
    borderRadius: 20,
  },
  searchBar: {
    overflow: 'hidden',
    backgroundColor: theme.colors.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    paddingHorizontal: theme.spacing.lg,
    justifyContent: 'center',
  },
  searchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 40,
    gap: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.text.primary,
    paddingVertical: 0,
  },
  filterRow: {
    flexDirection: 'row',
    backgroundColor: theme.colors.card,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    alignItems: 'center',
  },
  pillScroll: {
    maxHeight: 46,
    flexGrow: 0,
    minHeight: 46,
  },
  pillContent: {
    gap: 8,
    paddingRight: 16,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  pillActive: {
    backgroundColor: theme.colors.text.primary,
    borderColor: theme.colors.text.primary,
  },
  pillInactive: {
    backgroundColor: 'transparent',
    borderColor: theme.colors.border,
  },
  pillText: {
    fontSize: 13,
    letterSpacing: -0.1,
  },
  pillTextActive: {
    color: theme.colors.white,
    fontWeight: '700',
  },
  pillTextInactive: {
    color: theme.colors.text.secondary,
    fontWeight: '500',
  },
  subjectDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  listContent: {
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.lg,
    paddingBottom: 120,
    gap: 12,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
    color: theme.colors.text.secondary,
    textAlign: 'center',
  },
  fabContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
  },
  fab: {
    width: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  fabText: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.white,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.28)',
  },
  modalPressable: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 28,
    maxHeight: '80%',
  },
  editModalSheet: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: Platform.OS === 'ios' ? 60 : 52,
    minHeight: 300,
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  editModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  editModalClose: {
    padding: 4,
  },
  editLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: 8,
  },
  editInput: {
    backgroundColor: theme.colors.inputBackground,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: theme.colors.text.primary,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  editSubjectRow: {
    gap: 8,
    marginBottom: 24,
  },
  subjectChipWrapper: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  subjectChipActive: {
    borderColor: theme.colors.primary,
  },
  subjectChipInactive: {
    borderColor: theme.colors.border,
  },
  subjectChipDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  subjectChipLabel: {
    fontSize: 12,
  },
  subjectChipLabelActive: {
    color: theme.colors.primary,
    fontWeight: '700',
  },
  subjectChipLabelInactive: {
    color: theme.colors.text.secondary,
    fontWeight: '500',
  },
  saveBtn: {
    backgroundColor: theme.colors.primary,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  saveBtnText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 15,
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
  },
  menuContainer: {
    backgroundColor: theme.colors.card,
    borderRadius: 16,
    overflow: 'hidden',
    width: '100%',
    maxWidth: 280,
  },
  menuOption: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuOptionBorder: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  menuOptionText: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
});
