import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const gradesStyles = StyleSheet.create({
  header: globalStyles.standardHeader,
  logoText: globalStyles.screenTitle,
  termPill: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.inputBackground,
    paddingHorizontal: 12, paddingVertical: 6,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
  },
  termText: { fontSize: theme.typography.sizes.sm, fontWeight: '600', color: theme.colors.text.primary },
  filtersContainer: { padding: theme.spacing.md, gap: 8 },
  filterRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  filterPill: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 4,
    backgroundColor: theme.colors.inputBackground,
    paddingHorizontal: 12, paddingVertical: 8,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
  },
  filterText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, flex: 1 },
  applyBtn: {
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 20, paddingVertical: 8,
    borderRadius: theme.borderRadius.full,
  },
  applyBtnText: { color: theme.colors.text.inverse, fontWeight: '700', fontSize: theme.typography.sizes.sm },
  scroll: { paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.lg, gap: 16, paddingBottom: 40 },
  card: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg,
    borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  gpaRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  gpaLabel: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 2 },
  gpaValue: { fontSize: theme.typography.sizes.xxxl, fontWeight: '900', color: theme.colors.text.primary },
  divider: { width: 1, height: 50, backgroundColor: theme.colors.border, marginHorizontal: 12 },
  miniSparkline: { flexDirection: 'row', alignItems: 'flex-end', gap: 3, height: 40, marginLeft: 12 },
  miniBar: { width: 8, borderRadius: 2 },
  scaleText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 6 },
  projectedRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  projectedText: { fontSize: theme.typography.sizes.sm, color: theme.colors.text.secondary },
  editScaleText: { fontSize: theme.typography.sizes.sm, color: theme.colors.primary, fontWeight: '600' },
  section: { gap: 12 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  projectionHeaderRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 6,
  },
  sectionTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  addBtn: {
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 14, paddingVertical: 7,
    borderRadius: theme.borderRadius.full, marginLeft: 8,
  },
  addBtnText: { color: theme.colors.text.inverse, fontWeight: '700', fontSize: theme.typography.sizes.sm },
  bulkBtn: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1, borderColor: theme.colors.border,
  },
  assessCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.md,
    borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  assessTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 10 },
  assessIconBox: {
    width: 42, height: 42, borderRadius: 12,
    justifyContent: 'center', alignItems: 'center',
  },
  assessName: { fontSize: theme.typography.sizes.sm, fontWeight: '700', color: theme.colors.text.primary, marginBottom: 4 },
  tagsRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap', marginBottom: 4 },
  tag: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: theme.borderRadius.full },
  tagText: { fontSize: theme.typography.sizes.xs, fontWeight: '600', color: theme.colors.text.secondary },
  dateText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary },
  weightText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary },
  scoreBadge: { alignItems: 'flex-end' },
  scoreText: { fontSize: theme.typography.sizes.sm, fontWeight: '700' },
  scorePct: { fontSize: theme.typography.sizes.xl, fontWeight: '900' },
  progressBar: {
    height: 5, backgroundColor: theme.colors.inputBackground,
    borderRadius: 3, marginBottom: 10, overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 3 },
  assessActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  actionPill: {
    paddingHorizontal: 10, paddingVertical: 5,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
    backgroundColor: theme.colors.inputBackground,
  },
  actionPillText: { fontSize: theme.typography.sizes.xs, fontWeight: '600', color: theme.colors.text.secondary },
  deleteBtn: { borderColor: theme.colors.dangerTransparent, backgroundColor: theme.colors.dangerTransparent },
  fabAdd: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: theme.colors.text.primary,
    justifyContent: 'center', alignItems: 'center',
    marginLeft: 'auto',
  },
  currentProjectionCentered: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    marginBottom: 12,
  },
  currentProjectionLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'nowrap',
  },
  currentProjectionLabel: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
    fontWeight: '600',
    textAlign: 'center',
    flexShrink: 1,
  },
  currentProjectionValue: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.success,
    fontWeight: '800',
    textAlign: 'center',
  },
  descText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginVertical: 6 },
  simInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    marginBottom: 12,
  },
  simInputWrapper: {
    flex: 1,
    minWidth: 0,
  },
  simInputLabel: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.text.secondary,
    marginBottom: 4,
    fontWeight: '600',
  },
  simAddBtn: {
    backgroundColor: theme.colors.text.primary,
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  simInput: {
    flex: 1, backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.md, borderWidth: 1, borderColor: theme.colors.border,
    padding: 8, fontSize: theme.typography.sizes.sm, color: theme.colors.text.primary, textAlign: 'center',
  },
  simChartCard: {
    marginBottom: 12,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: '#DCE7F3',
    backgroundColor: '#EEF4FA',
    paddingVertical: 10,
    alignItems: 'center',
  },
  simChart: {
    borderRadius: theme.borderRadius.md,
  },
  simSummary: {
    backgroundColor: theme.colors.successTransparent, borderRadius: theme.borderRadius.md, padding: theme.spacing.sm, marginBottom: 12,
  },
  simSummaryText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, fontWeight: '600' },
  projGpaText: { fontSize: theme.typography.sizes.md, color: theme.colors.text.primary, fontWeight: '700', marginTop: 2 },
  simActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 2,
  },
  simActionPrimary: {
    minWidth: 118,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: theme.borderRadius.full,
    alignItems: 'center',
  },
  simActionPrimaryText: {
    color: theme.colors.text.inverse,
    fontWeight: '700',
    fontSize: theme.typography.sizes.sm,
  },
  simActionSecondary: {
    minWidth: 118,
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: theme.borderRadius.full,
    alignItems: 'center',
  },
  simActionSecondaryText: {
    color: theme.colors.text.primary,
    fontWeight: '700',
    fontSize: theme.typography.sizes.sm,
  },
  bulkCard: { borderLeftWidth: 3, borderLeftColor: theme.colors.primary },
  bulkCardInner: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  chooseFileText: { fontSize: theme.typography.sizes.sm, color: theme.colors.primary, fontWeight: '600', marginTop: 4 },
  smallBadgeBtn: {
    backgroundColor: theme.colors.primaryTransparent.light,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4,
    paddingHorizontal: 12, paddingVertical: 5,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1, borderColor: 'rgba(0,0,0,0.1)',
    minWidth: 105,
  },
  smallBadgeText: { color: theme.colors.text.primary, fontWeight: '700', fontSize: 11 },
});
