import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const settingsStyles = StyleSheet.create({
  header: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.md,
    borderBottomWidth: 1, borderBottomColor: theme.colors.border,
  },
  logoText: { fontSize: theme.typography.sizes.lg, fontWeight: '800', color: theme.colors.text.primary },
  cancelBtn: { paddingHorizontal: 14, paddingVertical: 7, marginRight: 8 },
  cancelText: { fontSize: 12, color: theme.colors.text.secondary, fontWeight: '600' },
  saveBtn: {
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 18, paddingVertical: 8,
    borderRadius: theme.borderRadius.full,
  },
  saveBtnText: { color: '#fff', fontWeight: '700', fontSize: 12 },
  scroll: { paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.lg, paddingBottom: 40 },
  profileCard: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.md,
    borderWidth: 1, borderColor: theme.colors.border,
    ...globalStyles.shadow, marginBottom: theme.spacing.xl,
  },
  profileAvatar: { width: 52, height: 52, borderRadius: 26, borderWidth: 2, borderColor: theme.colors.border },
  profileName: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  profileEmail: { fontSize: 11, color: theme.colors.text.secondary },
  editBtn: {
    backgroundColor: theme.colors.inputBackground,
    paddingHorizontal: 12, paddingVertical: 4,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
  },
  editBtnText: { fontSize: 11, fontWeight: '600', color: theme.colors.text.primary },
  changePwText: { fontSize: 11, color: theme.colors.primary, fontWeight: '600' },
  section: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg,
    borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
    marginBottom: theme.spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start',
    marginBottom: 16, paddingBottom: 12,
    borderBottomWidth: 1, borderBottomColor: theme.colors.border,
  },
  sectionTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary, marginBottom: 2 },
  sectionDesc: { fontSize: 11, color: theme.colors.text.secondary },
  subSectionTitle: {
    fontSize: theme.typography.sizes.sm, fontWeight: '700', color: theme.colors.text.secondary,
    marginTop: 12, marginBottom: 8,
  },
  termsRow: { gap: 8, paddingVertical: 4, marginBottom: 12 },
  termChip: {
    paddingHorizontal: 14, paddingVertical: 6,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1, borderColor: theme.colors.border,
  },
  termChipActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  termChipText: { fontSize: 12, fontWeight: '600', color: theme.colors.text.secondary },
  termChipTextActive: { color: '#fff' },
  settingRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: theme.colors.border + '80',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border + '80',
  },
  actionRowTextWrap: {
    flex: 1,
    minWidth: 180,
    paddingRight: 8,
  },
  actionRowButtonWrap: {
    marginLeft: 'auto',
  },
  // Action Row Grid (50/50)
  actionRowGrid: {
    flexDirection: 'row',
    gap: 0,
    marginTop: 12,
  },
  actionGridColumn: {
    flex: 1,
    gap: 6,
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  actionGridColumnLeft: {
    borderRightWidth: 1,
    borderRightColor: theme.colors.border + '40',
    paddingRight: 12,
  },
  actionGridColumnRight: {
    paddingLeft: 12,
  },
  actionLabel: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    maxHeight: 44,
    overflow: 'hidden',
    textAlign: 'center',
  },
  settingTitle: { fontSize: theme.typography.sizes.sm, fontWeight: '600', color: theme.colors.text.primary, marginBottom: 2 },
  settingDesc: { fontSize: 11, color: theme.colors.text.secondary },
  thresholdRow: {
    flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 4,
  },
  thresholdInput: {
    width: 60, textAlign: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.md, borderWidth: 1, borderColor: theme.colors.border,
    padding: 8, fontSize: 18, fontWeight: '800', color: theme.colors.text.primary,
    marginTop: 6,
  },
  scaleRow: {
    flexDirection: 'row', alignItems: 'center', paddingVertical: 10,
    borderBottomWidth: 1, borderBottomColor: theme.colors.border + '60',
  },
  activeBadge: {
    backgroundColor: '#34C75920', paddingHorizontal: 10, paddingVertical: 4,
    borderRadius: theme.borderRadius.full,
  },
  activeBadgeText: { fontSize: 11, fontWeight: '700', color: '#34C759' },
  selectText: { fontSize: 12, color: theme.colors.primary, fontWeight: '600' },
  lmsRow: {
    flexDirection: 'row', alignItems: 'center', paddingVertical: 10,
    borderBottomWidth: 1, borderBottomColor: theme.colors.border + '60',
  },
  exportRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  exportBtn: {
    backgroundColor: theme.colors.text.primary,
    paddingVertical: 10, borderRadius: theme.borderRadius.full, alignItems: 'center',
  },
  exportBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  exportBtnOutline: {
    backgroundColor: theme.colors.background,
    borderWidth: 1, borderColor: theme.colors.border,
  },
  exportBtnOutlineText: { color: theme.colors.text.primary, fontWeight: '700', fontSize: 13 },
  openText: { fontSize: 12, color: theme.colors.primary, fontWeight: '700' },
  versionText: { fontSize: 11, color: theme.colors.text.secondary },
  darkPill: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 14, paddingVertical: 12,
    borderRadius: theme.borderRadius.full,
  },
  darkPillText: { color: '#fff', fontWeight: '700', fontSize: 12 },
  outlinePill: {
    paddingHorizontal: 12, paddingVertical: 6,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1, borderColor: theme.colors.border,
    backgroundColor: theme.colors.inputBackground,
  },
  outlinePillText: { fontSize: 11, fontWeight: '600', color: theme.colors.text.secondary },
  modalOverlay: {
    flex: 1, backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center', alignItems: 'center',
    padding: theme.spacing.xl,
  },
  modalContent: {
    backgroundColor: theme.colors.background,
    width: '100%', maxWidth: 400,
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.xl,
    ...globalStyles.shadow,
  },
  modalHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: theme.spacing.lg,
  },
  modalTitle: { fontSize: theme.typography.sizes.lg, fontWeight: '800', color: theme.colors.text.primary },
  modalBody: { gap: theme.spacing.md, marginBottom: theme.spacing.xl },
  modalLabel: { fontSize: theme.typography.sizes.sm, fontWeight: '600', color: theme.colors.text.primary, marginBottom: 4 },
  modalDesc: { fontSize: 12, color: theme.colors.text.secondary, lineHeight: 18 },
  modalInput: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1, borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: theme.spacing.md, paddingVertical: 12,
    fontSize: theme.typography.sizes.md, color: theme.colors.text.primary,
  },
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: theme.spacing.md },
  modalBtnSecondary: {
    paddingHorizontal: 16, paddingVertical: 10,
    borderRadius: theme.borderRadius.full,
  },
  modalBtnSecondaryText: { color: theme.colors.text.secondary, fontWeight: '600', fontSize: theme.typography.sizes.sm },
  modalBtnPrimary: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 20, paddingVertical: 10,
    borderRadius: theme.borderRadius.full,
  },
  modalBtnPrimaryText: { color: theme.colors.white, fontWeight: '700', fontSize: theme.typography.sizes.sm },
  actionButton: {
    width: 120,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: theme.borderRadius.full,
  },

  // ── Local AI Engine ──
  localAISection: {
    marginTop: 0,
  },
  modelCard: {
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 12,
  },
  modelCardActive: {
    borderColor: theme.colors.primary,
    borderWidth: 1.5,
  },
  modelCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  modelCardTitle: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  modelCardTag: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    marginTop: 1,
  },
  activeModelBadge: {
    backgroundColor: theme.colors.primary + '25',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: theme.borderRadius.full,
  },
  activeModelBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  modelCardDesc: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    lineHeight: 16,
    marginBottom: 8,
  },
  modelCardMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 6,
  },
  modelCardMetric: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    flexShrink: 1,
  },
  modelCardMetricLabel: {
    color: theme.colors.text.primary,
    fontWeight: '600',
  },
  modelCardCapabilities: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginBottom: 10,
  },
  modelCardCap: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: theme.borderRadius.full,
    overflow: 'hidden',
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  progressBarBg: {
    flex: 1,
    height: 6,
    backgroundColor: theme.colors.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 3,
  },
  progressText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.primary,
    minWidth: 32,
    textAlign: 'right',
  },
  modelCardActions: {
    flexDirection: 'row',
    gap: 8,
  },
  downloadBtn: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    paddingVertical: 10,
    borderRadius: theme.borderRadius.full,
    alignItems: 'center',
  },
  downloadBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 12,
  },
  deleteBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.inputBackground,
  },
  deleteBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.text.secondary,
  },
  storageBar: {
    marginTop: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  storageRow: {
    flexDirection: 'column',
  },
});
