import { StyleSheet } from 'react-native';
import { theme } from './theme';

export const thresholdStyles = StyleSheet.create({
  card: {
    backgroundColor: theme.colors.background,
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: theme.spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  labelGroup: {
    flex: 1,
  },
  rightControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoButton: {
    padding: 8,
  },
  eyebrow: {
    fontSize: 13,
    fontWeight: '800',
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 99,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginVertical: 16,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 20,
  },
  percentBlock: {
    alignItems: 'center',
    minWidth: 72,
  },
  percentValue: {
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -1.5,
    lineHeight: 36,
  },
  percentSign: {
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0,
  },
  percentLabel: {
    marginTop: 2,
    fontSize: 10,
    color: theme.colors.text.secondary,
    fontWeight: '600',
    textTransform: 'lowercase',
    textAlign: 'center',
  },
  neededBlock: {
    flex: 1,
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    padding: 14,
    gap: 6,
  },
  neededHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  neededIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  neededTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  neededValue: {
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: -0.1,
    lineHeight: 20,
    textAlign: 'justify',
  },
  trackWrap: {
    gap: 6,
  },
  track: {
    height: 10,
    borderRadius: 99,
    backgroundColor: theme.colors.inputBackground,
    overflow: 'visible',
    position: 'relative',
  },
  fill: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    borderRadius: 99,
  },
  midMarker: {
    position: 'absolute',
    left: '50%',
    top: -2,
    width: 2,
    height: 14,
    borderRadius: 1,
    backgroundColor: theme.colors.border,
  },
  trackLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  trackLabel: {
    fontSize: 10,
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
});
