import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

const SPACING = {
  PAGE: 20,
  SECTION: 16,
  CARD: 14,
  INNER: 8,
  TIGHT: 4,
};

export const subjectsStyles = StyleSheet.create({
  header: globalStyles.standardHeader,
  headerTitle: globalStyles.screenTitle,
  addBtn: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: theme.colors.text.primary,
    justifyContent: 'center', alignItems: 'center',
  },
  searchRow: {
    flexDirection: 'row', alignItems: 'center', gap: SPACING.INNER,
    paddingHorizontal: SPACING.PAGE, paddingVertical: SPACING.INNER,
  },
  searchBox: {
    flex: 1, flexDirection: 'row', alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
    paddingHorizontal: SPACING.CARD, height: 36,
  },
  searchInput: { flex: 1, fontSize: theme.typography.sizes.sm, color: theme.colors.text.primary },
  filterBtn: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1, borderColor: theme.colors.border,
  },
  scroll: { paddingHorizontal: SPACING.PAGE, paddingTop: SPACING.INNER, paddingBottom: 40 },
  section: { marginBottom: SPACING.SECTION },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: SPACING.INNER },
  sectionTitle: { fontSize: theme.typography.sizes.sm, fontWeight: '800', color: theme.colors.text.secondary, textTransform: 'uppercase', letterSpacing: 0.8 },
  sectionHint: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary },

  // ── Semester Hero ──
  semesterHero: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: SPACING.CARD,
    marginBottom: SPACING.SECTION,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#000',
    shadowRadius: 6,
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  gpaAmbientGlow: {
    position: 'absolute',
    top: '-20%',
    left: '-10%',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(99, 102, 241, 0.05)',
  },
  heroArc1: {
    position: 'absolute',
    top: '50%',
    left: '18%',
    width: 120, height: 120,
    marginTop: -60, marginLeft: -60,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.08)',
    backgroundColor: 'transparent',
  },
  heroArc2: {
    position: 'absolute',
    top: '50%',
    left: '18%',
    width: 170, height: 170,
    marginTop: -85, marginLeft: -85,
    borderRadius: 85,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.05)',
    backgroundColor: 'transparent',
  },
  heroArc3: {
    position: 'absolute',
    top: '50%',
    left: '18%',
    width: 230, height: 230,
    marginTop: -115, marginLeft: -115,
    borderRadius: 115,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.03)',
    backgroundColor: 'transparent',
  },
  heroContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  heroEngineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flexWrap: 'wrap',
    marginHorizontal: -SPACING.CARD,
    marginBottom: -SPACING.CARD,
    marginTop: SPACING.CARD,
    paddingVertical: 10,
    paddingHorizontal: SPACING.CARD,
    backgroundColor: theme.colors.card,
    borderTopWidth: 0.5,
    borderTopColor: theme.colors.border,
  },
  heroEngineChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  heroEngineSep: {
    fontSize: 10,
    color: theme.colors.text.secondary,
    fontWeight: '300',
  },
  heroEngineIcon: { fontSize: 10 },
  heroEngineText: {
    fontSize: 10,
    fontWeight: '600',
    color: theme.colors.text.primary,
    letterSpacing: 0.1,
  },
  gpaContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '35%',
  },
  miniGridContainer: {
    width: '62%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  miniCard: {
    width: '47%',
    backgroundColor: theme.colors.card,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: theme.colors.border,
  },
  miniCardInRisk: {
    width: '47%',
    backgroundColor: 'rgba(255,45,85,0.04)',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255,45,85,0.12)',
  },
  miniCardTitle: {
    fontSize: 8,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  miniCardTitleRisk: {
    fontSize: 8,
    fontWeight: '700',
    color: '#FF8787',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  miniCardValue: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.text.primary,
    fontFamily: 'monospace',
    letterSpacing: -0.5,
  },
  miniCardValueRisk: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FF8787',
    fontFamily: 'monospace',
    letterSpacing: -0.5,
  },
  miniCardSub: {
    fontSize: 10,
    fontWeight: '300',
    color: theme.colors.text.secondary,
  },
  semesterGpaCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: '#6366f1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(99, 102, 241, 0.06)',
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  semesterGpaValue: {
    fontSize: 28, fontWeight: '200', color: theme.colors.text.primary,
    letterSpacing: -1,
  },
  semesterGpaLabel: {
    fontSize: 7, fontWeight: '600', color: theme.colors.text.secondary,
    textTransform: 'uppercase', letterSpacing: 0.8, marginTop: -2,
  },

  // ── Critical Section (Compact List) ──
  criticalSection: { marginBottom: SPACING.SECTION },
  criticalHeader: {
    flexDirection: 'row', alignItems: 'center',
    marginBottom: SPACING.INNER,
    gap: 6,
  },
  criticalIcon: {
    fontSize: 13,
  },
  criticalTitle: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
    color: theme.colors.text.secondary,
  },
  criticalCount: {
    fontSize: theme.typography.sizes.xs,
    fontWeight: '700',
    color: theme.colors.text.secondary,
  },
  criticalList: {
    gap: 6,
  },
  criticalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    gap: 10,
  },
  criticalDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  criticalRowName: {
    flex: 1,
    fontSize: theme.typography.sizes.md,
    fontWeight: '600',
    color: theme.colors.text.primary,
  },
  criticalRowScore: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '800',
    color: theme.colors.danger,
    minWidth: 28,
    textAlign: 'right',
  },
  criticalRowAction: {
    backgroundColor: theme.colors.text.primary,
    borderRadius: theme.borderRadius.full,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  criticalRowActionText: {
    color: theme.colors.text.inverse,
    fontWeight: '700',
    fontSize: 10,
  },

  // ── Timeline (Compact) ──
  timelineSection: { marginBottom: SPACING.SECTION },
  timelineHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: SPACING.INNER,
  },
  timelineTitle: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  timelineCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 10, padding: 12,
    borderWidth: 1, borderColor: theme.colors.border,
  },
  timelineItem: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 10,
    paddingVertical: 5,
  },
  timelineDot: {
    width: 8, height: 8, borderRadius: 4,
    marginTop: 4,
  },
  timelineLine: {
    position: 'absolute', left: 3.5, top: 16, bottom: 0,
    width: 1, backgroundColor: theme.colors.border,
  },
  timelineContent: { flex: 1 },
  timelineName: { fontSize: 12, fontWeight: '700', color: theme.colors.text.primary },
  timelineMeta: { fontSize: 10, color: theme.colors.text.secondary, marginTop: 1 },
  timelineTime: { fontSize: 9, fontWeight: '600', color: theme.colors.text.secondary },

  // ── Bento Grid ──
  gridSection: { marginBottom: SPACING.SECTION },
  gridHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: SPACING.INNER,
  },
  gridTitle: {
    fontSize: theme.typography.sizes.sm, fontWeight: '700', color: theme.colors.text.secondary,
    textTransform: 'uppercase', letterSpacing: 0.8,
  },
  gridCount: { fontSize: 10, fontWeight: '800', color: theme.colors.text.secondary },
  grid: {
    flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -5,
  },
  gridCol: {
    width: '50%', padding: 5,
  },
  gridCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 12, padding: 12,
    borderWidth: 1, borderColor: theme.colors.border,
  },
  gridTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 6 },
  gridIcon: {
    width: 32, height: 32, borderRadius: 8,
    justifyContent: 'center', alignItems: 'center',
  },
  gridScoreGroup: { alignItems: 'flex-end' },
  gridScoreRow: { flexDirection: 'row', alignItems: 'baseline', gap: 2 },
  gridScore: { fontSize: 20, fontWeight: '900', letterSpacing: -0.5 },
  gridScoreMax: { fontSize: 9, fontWeight: '600', color: theme.colors.text.secondary },
  gridDelta: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  gridDeltaText: { fontSize: 10, fontWeight: '800' },
  gridBody: { marginBottom: 4 },
  gridName: { fontSize: 12, fontWeight: '700', color: theme.colors.text.primary, marginBottom: 1 },
  gridProf: { fontSize: 9, color: theme.colors.text.secondary, marginBottom: 3 },
  gridMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: 6 },
  gridMetaBadge: { backgroundColor: theme.colors.primaryTransparent.light, borderRadius: 4, paddingHorizontal: 5, paddingVertical: 1 },
  gridMetaBadgeText: { fontSize: 8, fontWeight: '700', color: theme.colors.text.secondary },
  gridTargetText: { fontSize: 8, color: theme.colors.text.secondary, fontWeight: '600' },
  gridProgress: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  gridProgressTrack: { flex: 1, height: 3, backgroundColor: theme.colors.inputBackground, borderRadius: 1.5, overflow: 'hidden' },
  gridProgressFill: { height: '100%', borderRadius: 1.5 },
  gridProgressText: { fontSize: 9, fontWeight: '700', color: theme.colors.text.secondary, minWidth: 26, textAlign: 'right' },
  dueMiniBadge: {
    backgroundColor: 'rgba(230, 126, 34, 0.08)',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
    alignSelf: 'flex-start',
    marginTop: 3,
  },
  dueMiniText: {
    color: '#e67e22',
    fontSize: 9,
    fontWeight: '600',
  },
  gridNextMilestone: {
    fontSize: 10,
    color: theme.colors.text.secondary,
    marginBottom: 3,
    fontWeight: '500',
  },

  // ── Schedule Grid ──
  scheduleGridSection: { marginBottom: SPACING.SECTION, width: '100%' },
  scheduleGridHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: SPACING.INNER,
  },
  scheduleGridTitle: {
    fontSize: theme.typography.sizes.sm, fontWeight: '700', color: theme.colors.text.secondary,
    textTransform: 'uppercase', letterSpacing: 0.8,
  },
  scheduleGridContainer: {
    width: '100%',
    backgroundColor: theme.colors.background,
    borderRadius: 10, padding: 8,
    borderWidth: 1, borderColor: theme.colors.border,
  },
  sgRow: { flexDirection: 'row' },
  sgTimeCol: { width: 28, justifyContent: 'center', alignItems: 'center', height: 20 },
  sgTimeText: { fontSize: 7, color: theme.colors.text.secondary, fontWeight: '600' },
  sgDayCol: { flex: 1, alignItems: 'center', justifyContent: 'center', height: 24 },
  sgDayText: { fontSize: 7, fontWeight: '800', color: theme.colors.text.secondary },
  sgCell: {
    flex: 1, height: 20,
    justifyContent: 'center', alignItems: 'center',
    borderLeftWidth: 0.5, borderBottomWidth: 0.5,
    borderColor: theme.colors.border + '30',
  },
  sgBlock: {
    width: '50%', height: 4, borderRadius: 2,
  },

  // ── Calculator ──
  calcCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 14, padding: SPACING.CARD,
    marginBottom: 16, borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  calcInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  calcEmptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 24 },
  calcEmptyText: { color: theme.colors.text.secondary, marginTop: 8, fontSize: theme.typography.sizes.sm, textAlign: 'center' },
  calcMaxBox: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: theme.colors.border },
  calcMaxLabel: { fontSize: theme.typography.sizes.xs, color: '#FF9500', marginBottom: 3 },
  calcMaxValue: { fontSize: 16, fontWeight: '900', color: '#FF9500', textAlign: 'center' },
  calcHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: theme.colors.border },
  calcTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  calcSubject: { fontSize: theme.typography.sizes.sm, color: theme.colors.primary, fontWeight: '600', textAlign: 'right' },
  calcLabelsRow: { flexDirection: 'row', gap: 10, marginBottom: 6 },
  calcLabelBox: { flex: 1 },
  calcInputsRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  calcInputBox: { flex: 1 },
  calcInputLabel: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 0, textAlign: 'center', fontWeight: '500', minHeight: 14 },
  calcInput: {
    width: '100%', textAlign: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.sm, borderWidth: 1, borderColor: theme.colors.border,
    padding: 10, fontSize: theme.typography.sizes.md, fontWeight: '700',
    color: theme.colors.text.primary, height: 40,
  },
  calcHint: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 10, textAlign: 'center', fontStyle: 'italic' },
  calcResult: { fontSize: 36, fontWeight: '900', textAlign: 'center', marginBottom: 2, marginTop: 6, color: theme.colors.primary },
  calcStatus: { fontSize: theme.typography.sizes.sm, fontWeight: '700', textAlign: 'center', marginBottom: 12 },
  statusBar: { flexDirection: 'row', height: 5, marginBottom: 6, borderRadius: 2.5, overflow: 'hidden', marginTop: 10 },
  statusSegment: { flex: 1 },
  statusLegend: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 14, paddingHorizontal: 4 },
  legendText: { fontSize: theme.typography.sizes.xs, fontWeight: '600' },
  calcActions: { flexDirection: 'row', gap: 8, paddingTop: 4, alignItems: 'center' },
  calcBtn: {
    flex: 1, backgroundColor: theme.colors.text.primary,
    borderRadius: theme.borderRadius.full, alignItems: 'center', justifyContent: 'center',
    height: 40,
  },
  calcBtnText: { color: theme.colors.text.inverse, fontWeight: '700', fontSize: theme.typography.sizes.sm, textAlign: 'center' },
  calcBtnSecondary: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border, flex: 1.1 },
  calcBtnReset: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border, paddingHorizontal: 12, borderRadius: theme.borderRadius.full, alignItems: 'center', justifyContent: 'center', height: 40 },
  calcBtnSecText: { color: theme.colors.text.primary, fontWeight: '600', fontSize: theme.typography.sizes.sm, textAlign: 'center' },

  // ── Assessments ──
  assessCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 14, padding: SPACING.CARD,
    borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  assessHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  assessHeaderIcon: { backgroundColor: theme.colors.primaryTransparent.light, padding: 5, borderRadius: 6 },
  assessStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  assessStatusDot: { width: 5, height: 5, borderRadius: 2.5 },
  assessStatusText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, fontWeight: '600' },
  assessEmptyState: { alignItems: 'center', paddingVertical: 24 },
  assessEmptyText: { color: theme.colors.text.secondary, marginTop: 4, fontSize: 12, textAlign: 'center', paddingHorizontal: 16 },
  assessScoreBadge: { backgroundColor: 'transparent', paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4, marginTop: 3 },
  assessScoreLabel: { fontSize: 9, fontWeight: '700' },
  assessHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: SPACING.INNER },
  assessTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary, flex: 1 },
  addAssessBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 8, paddingVertical: 5, borderRadius: theme.borderRadius.full,
  },
  addAssessBtnText: { color: theme.colors.text.inverse, fontSize: theme.typography.sizes.xs, fontWeight: '700' },

  assessList: { marginTop: 6 },
  assessRow: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingVertical: 8, borderBottomWidth: 0.5, borderBottomColor: 'rgba(0,0,0,0.04)',
  },
  assessIcon: {
    width: 18, height: 18,
    justifyContent: 'center', alignItems: 'center',
  },
  assessBody: { flex: 1 },
  assessName: { fontSize: theme.typography.sizes.md, fontWeight: '600', color: theme.colors.text.primary, marginBottom: 1 },
  assessMeta: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, letterSpacing: 0.2 },

  assessRight: { alignItems: 'flex-end' },
  assessScore: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },

  sparklineContainer: { marginTop: 10, paddingVertical: 10 },
  sparklineLabel: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  sparklineWrapper: { flexDirection: 'row', gap: 10, alignItems: 'flex-end', marginTop: 6 },
  sparklineYAxis: { width: 18, height: 50, position: 'relative' },
  yAxisLabel: {
    fontSize: theme.typography.sizes.xs,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    textAlign: 'right',
    position: 'absolute',
    right: 0,
  },
  sparklineMain: { flex: 1, height: 50, borderLeftWidth: 1, borderLeftColor: 'rgba(0,0,0,0.04)', paddingLeft: 6 },
  sparkline: { flexDirection: 'row', alignItems: 'flex-end', gap: 5, height: 50 },
  sparkBar: { flex: 1, borderRadius: 2 },
  photoRow: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingTop: 10, borderTopWidth: 1, borderTopColor: theme.colors.border,
  },
  photoText: { flex: 1, fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary },
  photoBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 8, paddingVertical: 5, borderRadius: theme.borderRadius.full,
  },
  photoBtnText: { color: theme.colors.text.inverse, fontSize: theme.typography.sizes.xs, fontWeight: '700' },
});
