import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const subjectsStyles = StyleSheet.create({
  header: globalStyles.standardHeader,
  headerTitle: globalStyles.screenTitle,
  addBtn: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: theme.colors.text.primary,
    justifyContent: 'center', alignItems: 'center',
  },
  searchRow: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.sm,
  },
  searchBox: {
    flex: 1, flexDirection: 'row', alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
    paddingHorizontal: theme.spacing.md, height: 40,
  },
  searchInput: { flex: 1, fontSize: theme.typography.sizes.sm, color: theme.colors.text.primary },
  filterBtn: {
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1, borderColor: theme.colors.border,
  },
  scroll: { paddingHorizontal: theme.spacing.lg, paddingTop: theme.spacing.sm, paddingBottom: 40 },
  section: { marginBottom: 12 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  sectionHint: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary },
  // ── Semester Hero ──
  semesterHero: {
    backgroundColor: '#0D0E12',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#000',
    shadowRadius: 12,
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  gpaAmbientGlow: {
    position: 'absolute',
    top: '-20%',
    left: '-10%',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(99, 102, 241, 0.12)',
    shadowColor: '#6366f1',
    shadowRadius: 40,
    shadowOpacity: 1,
    elevation: 20,
  },
  heroContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  heroEngineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flexWrap: 'wrap',
    marginHorizontal: -18,
    marginBottom: -18,
    marginTop: 18,
    paddingVertical: 12,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderTopWidth: 0.5,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  heroEngineChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  heroEngineSep: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '300',
  },
  heroEngineIcon: {
    fontSize: 11,
  },
  heroEngineText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#FFFFFF',
    letterSpacing: 0.1,
  },
  gpaContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '35%',
  },
  miniGridContainer: {
    width: '62%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  miniCard: {
    width: '47%',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255, 255, 255, 0.07)',
  },
  miniCardInRisk: {
    width: '47%',
    backgroundColor: 'rgba(255,45,85,0.05)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: 'rgba(255,45,85,0.15)',
  },
  miniCardTitle: {
    fontSize: 9,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  miniCardTitleRisk: {
    fontSize: 9,
    fontWeight: '700',
    color: '#FF8787',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  miniCardValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#F5F6FA',
    fontFamily: 'monospace',
    letterSpacing: -0.5,
  },
  miniCardValueRisk: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FF8787',
    fontFamily: 'monospace',
    letterSpacing: -0.5,
  },
  miniCardSub: {
    fontSize: 11,
    fontWeight: '300',
    color: '#FFFFFF',
  },
  semesterGpaCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: '#6366f1', 
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  semesterGpaValue: {
    fontSize: 34, fontWeight: '200', color: '#F5F6FA',
    letterSpacing: -1,
  },
  semesterGpaLabel: {
    fontSize: 8, fontWeight: '600', color: '#FFFFFF',
    textTransform: 'uppercase', letterSpacing: 0.8, marginTop: -2,
  },
  // ── Critical Carousel ──
  criticalSection: { marginBottom: 16 },
  criticalHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: 10,
  },
  criticalTitle: {
    fontSize: 13, fontWeight: '800', color: theme.colors.text.secondary,
    textTransform: 'uppercase', letterSpacing: 1,
  },
  criticalBadge: {
    backgroundColor: theme.colors.dangerTransparent,
    paddingHorizontal: 8, paddingVertical: 3, borderRadius: theme.borderRadius.full,
  },
  criticalBadgeText: { fontSize: 10, fontWeight: '800', color: theme.colors.danger },
  criticalScroll: { flexGrow: 0 },
  criticalCard: {
    width: 190, backgroundColor: theme.colors.background,
    borderRadius: 16, padding: 14,
    borderWidth: 1, borderColor: theme.colors.border,
    ...globalStyles.shadow,
    marginRight: 10,
  },
  criticalCardTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  criticalCardDot: { width: 10, height: 10, borderRadius: 5 },
  criticalCardName: { flex: 1, fontSize: 13, fontWeight: '700', color: theme.colors.text.primary },
  criticalCardScore: { fontSize: 22, fontWeight: '900', color: theme.colors.danger, textAlign: 'center', marginBottom: 4 },
  criticalCardDelta: { fontSize: 10, fontWeight: '700', color: theme.colors.text.secondary, textAlign: 'center', marginBottom: 8 },
  criticalCardAction: {
    backgroundColor: theme.colors.danger,
    borderRadius: theme.borderRadius.full, paddingVertical: 6, alignItems: 'center',
  },
  criticalCardActionText: { color: theme.colors.white, fontWeight: '800', fontSize: 11 },
  criticalEmpty: {
    borderRadius: 16, borderWidth: 1, borderColor: theme.colors.border,
    borderStyle: 'dashed', paddingVertical: 24, alignItems: 'center',
  },
  criticalEmptyText: { fontSize: 11, color: theme.colors.text.secondary, fontWeight: '600' },
  // ── Timeline ──
  timelineSection: { marginBottom: 16 },
  timelineHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: 12,
  },
  timelineTitle: {
    fontSize: 13, fontWeight: '800', color: theme.colors.text.secondary,
    textTransform: 'uppercase', letterSpacing: 1,
  },
  timelineCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 16, padding: theme.spacing.md,
    borderWidth: 1, borderColor: theme.colors.border,
    ...globalStyles.shadow,
  },
  timelineItem: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 12,
    paddingVertical: 6,
  },
  timelineDot: {
    width: 10, height: 10, borderRadius: 5,
    marginTop: 4,
  },
  timelineLine: {
    position: 'absolute', left: 4.5, top: 18, bottom: 0,
    width: 1, backgroundColor: theme.colors.border,
  },
  timelineContent: { flex: 1 },
  timelineName: { fontSize: 13, fontWeight: '700', color: theme.colors.text.primary },
  timelineMeta: { fontSize: 10, color: theme.colors.text.secondary, marginTop: 1 },
  timelineTime: { fontSize: 10, fontWeight: '600', color: theme.colors.text.secondary },
  // ── Bento Grid ──
  gridSection: { marginBottom: 16 },
  gridHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: 12,
  },
  gridTitle: {
    fontSize: 13, fontWeight: '800', color: theme.colors.text.secondary,
    textTransform: 'uppercase', letterSpacing: 1,
  },
  gridCount: { fontSize: 10, fontWeight: '800', color: theme.colors.text.secondary },
  grid: {
    flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -6,
  },
  gridCol: {
    width: '50%', padding: 6,
  },
  gridCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 16, padding: 14,
    borderWidth: 1, borderColor: theme.colors.border,
    ...globalStyles.shadow,
  },
  gridTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 8 },
  gridIcon: {
    width: 36, height: 36, borderRadius: 10,
    justifyContent: 'center', alignItems: 'center',
  },
  gridScoreGroup: { alignItems: 'flex-end' },
  gridScoreRow: { flexDirection: 'row', alignItems: 'baseline', gap: 2 },
  gridScore: { fontSize: 24, fontWeight: '900', letterSpacing: -0.5 },
  gridScoreMax: { fontSize: 10, fontWeight: '600', color: theme.colors.text.secondary },
  gridDelta: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  gridDeltaText: { fontSize: 11, fontWeight: '800' },
  gridBody: { marginBottom: 6 },
  gridName: { fontSize: 13, fontWeight: '700', color: theme.colors.text.primary, marginBottom: 1 },
  gridProf: { fontSize: 10, color: theme.colors.text.secondary, marginBottom: 4 },
  gridMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  gridMetaBadge: { backgroundColor: theme.colors.primaryTransparent.light, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  gridMetaBadgeText: { fontSize: 9, fontWeight: '700', color: theme.colors.text.secondary },
  gridTargetText: { fontSize: 9, color: theme.colors.text.secondary, fontWeight: '600' },
  gridProgress: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  gridProgressTrack: { flex: 1, height: 4, backgroundColor: theme.colors.inputBackground, borderRadius: 2, overflow: 'hidden' },
  gridProgressFill: { height: '100%', borderRadius: 2 },
  gridProgressText: { fontSize: 10, fontWeight: '700', color: theme.colors.text.secondary, minWidth: 30, textAlign: 'right' },
  dueMiniBadge: {
    backgroundColor: 'rgba(230, 126, 34, 0.1)',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  dueMiniText: {
    color: '#e67e22',
    fontSize: 10,
    fontWeight: '600',
  },
  gridNextMilestone: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    marginBottom: 4,
    fontWeight: '500',
  },
  // ── Schedule Grid ──
  scheduleGridSection: { marginBottom: 16 },
  scheduleGridHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: 12,
  },
  scheduleGridTitle: {
    fontSize: 13, fontWeight: '800', color: theme.colors.text.secondary,
    textTransform: 'uppercase', letterSpacing: 1,
  },
  scheduleGridContainer: {
    backgroundColor: theme.colors.background,
    borderRadius: 16, padding: 10,
    borderWidth: 1, borderColor: theme.colors.border,
    ...globalStyles.shadow,
  },
  sgRow: { flexDirection: 'row' },
  sgTimeCol: { width: 30, justifyContent: 'center', alignItems: 'center', height: 22 },
  sgTimeText: { fontSize: 8, color: theme.colors.text.secondary, fontWeight: '600' },
  sgDayCol: { flex: 1, alignItems: 'center', justifyContent: 'center', height: 26 },
  sgDayText: { fontSize: 8, fontWeight: '800', color: theme.colors.text.secondary },
  sgCell: {
    flex: 1, height: 22,
    justifyContent: 'center', alignItems: 'center',
    borderLeftWidth: 0.5, borderBottomWidth: 0.5,
    borderColor: theme.colors.border + '30',
  },
  sgBlock: {
    width: '50%', height: 5, borderRadius: 2.5,
  },
  // ── Calculator ──
  calcCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg,
    marginBottom: theme.spacing.xl, borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  calcInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  calcEmptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 32 },
  calcEmptyText: { color: theme.colors.text.secondary, marginTop: 12, fontSize: theme.typography.sizes.sm, textAlign: 'center' },
  calcMaxBox: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.colors.border },
  calcMaxLabel: { fontSize: theme.typography.sizes.xs, color: '#FF9500', marginBottom: 4 },
  calcMaxValue: { fontSize: 18, fontWeight: '900', color: '#FF9500', textAlign: 'center' },
  calcHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: theme.colors.border },
  calcTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  calcSubject: { fontSize: theme.typography.sizes.sm, color: theme.colors.primary, fontWeight: '600', textAlign: 'right' },
  calcLabelsRow: { flexDirection: 'row', gap: 12, marginBottom: 8 },
  calcLabelBox: { flex: 1 },
  calcInputsRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  calcInputBox: { flex: 1 },
  calcInputLabel: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 0, textAlign: 'center', fontWeight: '500', minHeight: 16 },
  calcInput: {
    width: '100%', textAlign: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.md, borderWidth: 1, borderColor: theme.colors.border,
    padding: 12, fontSize: theme.typography.sizes.md, fontWeight: '700',
    color: theme.colors.text.primary, height: 44,
  },
  calcHint: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 12, textAlign: 'center', fontStyle: 'italic' },
  calcResult: { fontSize: theme.typography.sizes.display, fontWeight: '900', textAlign: 'center', marginBottom: 2, marginTop: 8, color: theme.colors.primary },
  calcStatus: { fontSize: theme.typography.sizes.sm, fontWeight: '700', textAlign: 'center', marginBottom: 14 },
  statusBar: { flexDirection: 'row', height: 6, marginBottom: 8, borderRadius: 3, overflow: 'hidden', marginTop: 12 },
  statusSegment: { flex: 1 },
  statusLegend: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 18, paddingHorizontal: 4 },
  legendText: { fontSize: theme.typography.sizes.xs, fontWeight: '600' },
  calcActions: { flexDirection: 'row', gap: 8, paddingTop: 4, alignItems: 'center' },
  calcBtn: {
    flex: 1, backgroundColor: theme.colors.text.primary,
    borderRadius: theme.borderRadius.full, alignItems: 'center', justifyContent: 'center',
    height: 44,
  },
  calcBtnText: { color: theme.colors.text.inverse, fontWeight: '700', fontSize: theme.typography.sizes.sm, textAlign: 'center' },
  calcBtnSecondary: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border, flex: 1.1 },
  calcBtnReset: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border, paddingHorizontal: 14, borderRadius: theme.borderRadius.full, alignItems: 'center', justifyContent: 'center', height: 44 },
  calcBtnSecText: { color: theme.colors.text.primary, fontWeight: '600', fontSize: theme.typography.sizes.sm, textAlign: 'center' },
  // ── Assessments ──
  assessCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 30, padding: theme.spacing.lg,
    borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  assessHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  assessHeaderIcon: { backgroundColor: theme.colors.primaryTransparent.light, padding: 6, borderRadius: 8 },
  assessStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  assessStatusDot: { width: 6, height: 6, borderRadius: 3 },
  assessStatusText: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, fontWeight: '600' },
  assessEmptyState: { alignItems: 'center', paddingVertical: 32 },
  assessEmptyText: { color: theme.colors.text.secondary, marginTop: 4, fontSize: 13, textAlign: 'center', paddingHorizontal: 16 },
  assessScoreBadge: { backgroundColor: 'transparent', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, marginTop: 4 },
  assessScoreLabel: { fontSize: 10, fontWeight: '700' },
  assessHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  assessTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary, flex: 1 },
  addAssessBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.full,
  },
  addAssessBtnText: { color: theme.colors.text.inverse, fontSize: theme.typography.sizes.xs, fontWeight: '700' },
  
  assessList: { marginTop: 8 },
  assessRow: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    paddingVertical: 10, borderBottomWidth: 0.5, borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  assessIcon: {
    width: 20, height: 20,
    justifyContent: 'center', alignItems: 'center',
  },
  assessBody: { flex: 1 },
  assessName: { fontSize: theme.typography.sizes.md, fontWeight: '600', color: theme.colors.text.primary, marginBottom: 1 },
  assessMeta: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, letterSpacing: 0.2 },
  
  assessRight: { alignItems: 'flex-end' },
  assessScore: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  
  sparklineContainer: { marginTop: 12, paddingVertical: 12 },
  sparklineLabel: { fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary, marginBottom: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  sparklineWrapper: { flexDirection: 'row', gap: 12, alignItems: 'flex-end', marginTop: 8 },
  sparklineYAxis: { width: 20, height: 60, position: 'relative' },
  yAxisLabel: { 
    fontSize: theme.typography.sizes.xs, 
    fontWeight: '700', 
    color: theme.colors.text.secondary, 
    textAlign: 'right',
    position: 'absolute',
    right: 0,
  },
  sparklineMain: { flex: 1, height: 60, borderLeftWidth: 1, borderLeftColor: 'rgba(0,0,0,0.05)', paddingLeft: 8 },
  sparkline: { flexDirection: 'row', alignItems: 'flex-end', gap: 6, height: 60 },
  sparkBar: { flex: 1, borderRadius: 3 },
  photoRow: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.colors.border,
  },
  photoText: { flex: 1, fontSize: theme.typography.sizes.xs, color: theme.colors.text.secondary },
  photoBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.full,
  },
  photoBtnText: { color: theme.colors.text.inverse, fontSize: theme.typography.sizes.xs, fontWeight: '700' },
});
