import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const subjectsStyles = StyleSheet.create({
  header: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: theme.spacing.xl, paddingVertical: theme.spacing.md,
    borderBottomWidth: 1, borderBottomColor: theme.colors.border,
  },
  headerTitle: { fontSize: theme.typography.sizes.lg, fontWeight: '800', color: theme.colors.text.primary },
  addBtn: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: theme.colors.text.primary,
    justifyContent: 'center', alignItems: 'center',
  },
  searchRow: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: theme.spacing.xl, paddingVertical: theme.spacing.sm,
  },
  searchBox: {
    flex: 1, flexDirection: 'row', alignItems: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.full, borderWidth: 1, borderColor: theme.colors.border,
    paddingHorizontal: theme.spacing.md, height: 40,
  },
  searchInput: { flex: 1, fontSize: theme.typography.sizes.sm, color: theme.colors.text.primary },
  filterBtn: {
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1, borderColor: theme.colors.border,
  },
  pillsScroll: {
    paddingHorizontal: theme.spacing.xl,
    paddingVertical: theme.spacing.sm,
    maxHeight: 54,
  },
  pill: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 16, paddingVertical: 8, borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.inputBackground,
    marginRight: 10, borderWidth: 1, borderColor: theme.colors.border,
  },
  pillActive: {
    backgroundColor: theme.colors.text.primary,
    borderColor: theme.colors.text.primary,
  },
  pillColor: {
    width: 8, height: 8, borderRadius: 4,
  },
  pillText: {
    fontSize: 12, fontWeight: '600', color: theme.colors.text.secondary,
  },
  pillTextActive: {
    color: '#fff',
  },
  scroll: { paddingHorizontal: theme.spacing.xl, paddingTop: theme.spacing.sm, paddingBottom: 40 },
  section: { marginBottom: 12 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  sectionHint: { fontSize: 11, color: theme.colors.text.secondary },
  subjectCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.md,
    marginBottom: 16, borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  subjectCardSelected: { borderColor: theme.colors.primary, borderWidth: 1.5 },
  subjectTop: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  codeCircle: {
    width: 44, height: 44, borderRadius: 22,
    justifyContent: 'center', alignItems: 'center',
  },
  codeText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  subjectName: { fontSize: theme.typography.sizes.sm, fontWeight: '700', color: theme.colors.text.primary },
  subjectProf: { fontSize: 11, color: theme.colors.text.secondary },
  creditsText: { fontSize: 11, color: theme.colors.text.secondary, fontWeight: '600' },
  avgText: { fontSize: theme.typography.sizes.sm, fontWeight: '700' },
  progressBar: {
    height: 6, backgroundColor: theme.colors.inputBackground,
    borderRadius: 3, marginBottom: 10, overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 3 },
  subjectBottom: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  assessmentBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.full,
  },
  assessmentBtnText: { color: '#fff', fontWeight: '700', fontSize: 12 },
  iconAction: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: theme.colors.inputBackground,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 1, borderColor: theme.colors.border,
  },
  nextLabel: { flex: 1, fontSize: 10, color: theme.colors.text.secondary, textAlign: 'right' },
  // ── Calculator ──
  calcCard: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg,
    marginBottom: theme.spacing.xl, borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  calcHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: theme.colors.border },
  calcTitle: { fontSize: theme.typography.sizes.md, fontWeight: '800', color: theme.colors.text.primary },
  calcSubject: { fontSize: 12, color: theme.colors.primary, fontWeight: '600', textAlign: 'right' },
  calcLabelsRow: { flexDirection: 'row', gap: 12, marginBottom: 8 },
  calcLabelBox: { flex: 1 },
  calcInputsRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  calcInputBox: { flex: 1 },
  calcInputLabel: { fontSize: 10, color: theme.colors.text.secondary, marginBottom: 0, textAlign: 'center', fontWeight: '500', minHeight: 16 },
  calcInput: {
    width: '100%', textAlign: 'center',
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.md, borderWidth: 1, borderColor: theme.colors.border,
    padding: 12, fontSize: theme.typography.sizes.md, fontWeight: '700',
    color: theme.colors.text.primary, height: 44,
  },
  calcHint: { fontSize: 11, color: theme.colors.text.secondary, marginBottom: 12, textAlign: 'center', fontStyle: 'italic' },
  calcResult: { fontSize: 44, fontWeight: '900', textAlign: 'center', marginBottom: 2, marginTop: 8, color: theme.colors.primary },
  calcStatus: { fontSize: theme.typography.sizes.sm, fontWeight: '700', textAlign: 'center', marginBottom: 14 },
  statusBar: { flexDirection: 'row', height: 6, marginBottom: 8, borderRadius: 3, overflow: 'hidden', marginTop: 12 },
  statusSegment: { flex: 1 },
  statusLegend: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 18, paddingHorizontal: 4 },
  legendText: { fontSize: 10, fontWeight: '600' },
  calcActions: { flexDirection: 'row', gap: 8, paddingTop: 4, alignItems: 'center' },
  calcBtn: {
    flex: 1, backgroundColor: theme.colors.text.primary,
    borderRadius: theme.borderRadius.full, alignItems: 'center', justifyContent: 'center',
    height: 44,
  },
  calcBtnText: { color: '#fff', fontWeight: '700', fontSize: 13, textAlign: 'center' },
  calcBtnSecondary: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border, flex: 1.1 },
  calcBtnReset: { backgroundColor: theme.colors.inputBackground, borderWidth: 1, borderColor: theme.colors.border, paddingHorizontal: 14, borderRadius: theme.borderRadius.full, alignItems: 'center', justifyContent: 'center', height: 44 },
  calcBtnSecText: { color: theme.colors.text.primary, fontWeight: '600', fontSize: 12, textAlign: 'center' },
  // ── Assessments ──
  assessCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 30, padding: theme.spacing.lg,
    borderWidth: 1, borderColor: theme.colors.border, ...globalStyles.shadow,
  },
  assessHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  assessTitle: { fontSize: 14, fontWeight: '800', color: theme.colors.text.primary, flex: 1 },
  addAssessBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.full,
  },
  addAssessBtnText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  
  assessList: { marginTop: 8 },
  assessRow: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    paddingVertical: 10, borderBottomWidth: 0.5, borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  assessIcon: {
    width: 20, height: 20,
    justifyContent: 'center', alignItems: 'center',
  },
  assessBody: { flex: 1 },
  assessName: { fontSize: 13, fontWeight: '600', color: theme.colors.text.primary, marginBottom: 1 },
  assessMeta: { fontSize: 10, color: theme.colors.text.secondary, letterSpacing: 0.2 },
  
  assessRight: { alignItems: 'flex-end' },
  assessScore: { fontSize: 14, fontWeight: '800', color: theme.colors.text.primary },
  
  sparklineContainer: { marginTop: 12, paddingVertical: 12 },
  sparklineLabel: { fontSize: 10, color: theme.colors.text.secondary, marginBottom: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  sparklineWrapper: { flexDirection: 'row', gap: 12, alignItems: 'flex-end', marginTop: 8 },
  sparklineYAxis: { width: 20, height: 60, position: 'relative' },
  yAxisLabel: { 
    fontSize: 8, 
    fontWeight: '700', 
    color: theme.colors.text.secondary, 
    textAlign: 'right',
    position: 'absolute',
    right: 0,
  },
  sparklineMain: { flex: 1, height: 60, borderLeftWidth: 1, borderLeftColor: 'rgba(0,0,0,0.05)', paddingLeft: 8 },
  sparkline: { flexDirection: 'row', alignItems: 'flex-end', gap: 6, height: 60 },
  sparkBar: { flex: 1, borderRadius: 3 },
  photoRow: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.colors.border,
  },
  photoText: { flex: 1, fontSize: 11, color: theme.colors.text.secondary },
  photoBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: theme.colors.text.primary,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.full,
  },
  photoBtnText: { color: '#fff', fontSize: 11, fontWeight: '700' },
});
