import { StyleSheet } from 'react-native';
import { theme } from './theme';
import { globalStyles } from './globalStyles';

export const subjectDetailStyles = StyleSheet.create({
  scroll: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: 8,
    paddingBottom: 36,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
  },
  premiumLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  loadingLogoContainer: {
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  loadingLogoCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: `${theme.colors.primary}10`,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  loadingPulse: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: `${theme.colors.primary}30`,
  },
  premiumLoadingText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    letterSpacing: 2,
    marginBottom: 16,
  },
  loadingBarTrack: {
    width: 140,
    height: 2,
    backgroundColor: '#F0F0F0',
    borderRadius: 1,
    overflow: 'hidden',
  },
  loadingBarFill: {
    width: '40%',
    height: '100%',
    backgroundColor: theme.colors.primary,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.md,
  },
  headerBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: `${theme.colors.primary}12`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAction: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  heroCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 30,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: theme.spacing.lg,
    ...globalStyles.shadow,
  },
  heroInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  heroIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCopy: {
    flex: 1,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: theme.colors.text.primary,
    letterSpacing: -0.4,
  },
  heroSubtitle: {
    marginTop: 4,
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
  },
  heroMeta: {
    marginTop: 10,
    fontSize: 12,
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
  sectionBlock: {
    marginBottom: theme.spacing.lg,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: theme.colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  sectionHint: {
    marginTop: 4,
    fontSize: 11,
    color: theme.colors.text.secondary,
  },
  sectionLink: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  sectionChip: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.text.secondary,
    backgroundColor: theme.colors.inputBackground,
    borderRadius: theme.borderRadius.full,
    paddingHorizontal: 10,
    paddingVertical: 6,
    overflow: 'hidden',
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: theme.colors.background,
    borderRadius: 24,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...globalStyles.shadow,
  },
  statHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    minHeight: 36,
  },
  statIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    flex: 1,
    fontSize: 11,
    lineHeight: 14,
    color: theme.colors.text.secondary,
    fontWeight: '700',
  },
  statValue: {
    marginTop: 12,
    fontSize: 24,
    fontWeight: '800',
    color: theme.colors.text.primary,
    letterSpacing: -0.4,
  },
  statNote: {
    marginTop: 4,
    fontSize: 11,
    color: theme.colors.text.secondary,
    lineHeight: 14,
  },
  thresholdCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 30,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: theme.spacing.lg,
    ...globalStyles.shadow,
  },
  thresholdHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  thresholdTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.colors.text.primary,
    letterSpacing: -0.3,
  },
  thresholdSubtitle: {
    marginTop: 4,
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
  },
  thresholdBadge: {
    minWidth: 54,
    height: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  thresholdBadgeText: {
    color: theme.colors.white,
    fontSize: 15,
    fontWeight: '800',
  },
  thresholdNeed: {
    marginTop: 16,
    fontSize: 22,
    fontWeight: '800',
    color: theme.colors.text.primary,
    letterSpacing: -0.4,
  },
  thresholdHint: {
    marginTop: 6,
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.text.secondary,
  },
  thresholdTrackWrap: {
    marginTop: 18,
  },
  thresholdTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.inputBackground,
    overflow: 'hidden',
  },
  thresholdFill: {
    height: '100%',
    borderRadius: 999,
  },
  thresholdMetaRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  thresholdMetaLabel: {
    fontSize: 11,
    color: theme.colors.text.secondary,
    fontWeight: '600',
  },
  thresholdMetaValue: {
    fontSize: 11,
    color: theme.colors.text.primary,
    fontWeight: '700',
  },
  insightsCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.lg,
    gap: 16,
    ...globalStyles.shadow,
  },
  insightRow: {
    gap: 10,
  },
  insightTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  insightTextBlock: {
    flex: 1,
  },
  insightTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  insightMeta: {
    marginTop: 3,
    fontSize: 11,
    color: theme.colors.text.secondary,
  },
  insightScore: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.inputBackground,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  emptyStateCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingHorizontal: 10,
    gap: 8,
  },
  emptyStateTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  emptyStateText: {
    fontSize: 12,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    lineHeight: 17,
  },
  galleryIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: `${theme.colors.primary}15`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryCard: {
    backgroundColor: theme.colors.background,
    borderRadius: 30,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...globalStyles.shadow,
  },
  galleryGridSingle: {
    borderRadius: 18,
    overflow: 'hidden',
    height: 200,
  },
  galleryImageFull: {
    width: '100%',
    height: '100%',
  },
  galleryGridTwo: {
    flexDirection: 'row',
    gap: 6,
    height: 160,
  },
  galleryImageHalf: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  } as any,
  galleryGridThree: {
    flexDirection: 'row',
    gap: 6,
    height: 200,
  },
  galleryImageLeft: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  } as any,
  galleryGridThreeRight: {
    flex: 1,
    flexDirection: 'column',
    gap: 6,
  },
  galleryImageQuarter: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  } as any,
  galleryGridFour: {
    flexDirection: 'column',
    gap: 6,
    height: 200,
  },
  galleryGridFourRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 6,
  },
  galleryImageQuad: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  } as any,
  galleryFooter: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  galleryFooterTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: theme.colors.text.primary,
  },
  galleryFooterText: {
    marginTop: 3,
    fontSize: 11,
    color: theme.colors.text.secondary,
  },
  galleryFooterAction: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    zIndex: 999,
  },
  cameraView: {
    flex: 1,
  },
  cameraControls: {
    position: 'absolute',
    bottom: 48,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 32,
  },
  cameraCancelBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraShutterBtn: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: theme.colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  cameraShutterInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.white,
  },
  detailLoadingRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  detailLoadingText: {
    fontSize: 11,
    color: theme.colors.text.secondary,
  },
  fabContainer: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    zIndex: 100,
  },
  fabButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...globalStyles.shadow,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
});
