import { StyleSheet } from 'react-native';
import { theme } from './theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  title: {
    color: theme.colors.text.primary,
    fontSize: 18,
    fontWeight: '700',
  },
  subtitle: {
    color: theme.colors.text.secondary,
    fontSize: 13,
    marginTop: 2,
  },
  closeBtn: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.card,
  },
  scroll: {
    flex: 1,
  },
  stepContainer: {
    padding: 20,
    flexGrow: 1,
  },
  centerStep: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  milestonePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primaryTransparent.light,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 16,
    alignSelf: 'flex-start',
  },
  milestoneEmoji: { fontSize: 14, marginRight: 6 },
  milestoneText: { color: theme.colors.primary, fontSize: 12, fontWeight: '600' },
  label: {
    color: theme.colors.text.secondary,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  notesInput: {
    backgroundColor: theme.colors.inputBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    padding: 16,
    color: theme.colors.text.primary,
    fontSize: 14,
    lineHeight: 22,
    flex: 1,
    minHeight: 120,
  },
  charCount: {
    color: theme.colors.text.placeholder,
    fontSize: 11,
    textAlign: 'right',
    marginTop: 4,
    marginBottom: 20,
  },
  imagesSection: {
    marginBottom: 20,
  },
  imagesSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  addImageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: theme.colors.primaryTransparent.light,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  addImageBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  imagesScroll: {
    flexGrow: 0,
  },
  imageThumb: {
    width: 90,
    height: 90,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  thumbImage: {
    width: '100%',
    height: '100%',
  },
  thumbOrder: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  thumbOrderText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },
  thumbRemove: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  emptyImagesHint: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderStyle: 'dashed',
    borderRadius: 16,
    paddingVertical: 24,
    alignItems: 'center',
    gap: 8,
  },
  emptyImagesText: {
    fontSize: 12,
    color: theme.colors.text.placeholder,
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  extractingTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text.primary,
    marginTop: 8,
  },
  extractingSubtitle: {
    fontSize: 13,
    color: theme.colors.text.secondary,
  },
  extractingDots: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  extractingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.border,
  },
  extractingDotActive: {
    backgroundColor: theme.colors.primary,
    transform: [{ scale: 1.3 }],
  },
  extractingDotDone: {
    backgroundColor: theme.colors.success,
  },
  primaryBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    padding: 16,
    gap: 8,
    marginTop: 4,
  },
  primaryBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  primaryBtnEmoji: { fontSize: 16 },
  previewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  previewCount: {
    color: theme.colors.text.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  backLink: {
    color: theme.colors.primary,
    fontSize: 13,
  },
  cardsList: {
    flex: 1,
    marginBottom: 16,
  },
  cardPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  cardRemoved: {
    borderColor: theme.colors.danger + '40',
    backgroundColor: theme.colors.dangerTransparent,
  },
  cardContent: { flex: 1, paddingRight: 10 },
  cardFront: {
    color: theme.colors.text.primary,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  cardBack: {
    color: theme.colors.text.secondary,
    fontSize: 12,
  },
  removeBtn: { padding: 4 },
  dirLabel: {
    color: theme.colors.text.secondary,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  dirRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  dirPill: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    alignItems: 'center',
    gap: 2,
    backgroundColor: theme.colors.inputBackground,
  },
  dirPillActive: {
    borderColor: '#5C6BC0',
    backgroundColor: '#EDE7F6',
  },
  dirIcon: {
    fontSize: 16,
    color: theme.colors.text.secondary,
  },
  dirIconActive: {
    color: '#5C6BC0',
  },
  dirPillLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: theme.colors.text.secondary,
    textAlign: 'center',
  },
  dirPillLabelActive: {
    color: '#5C6BC0',
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  pickerContent: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  pickerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.text.primary,
  },
  pickerClose: {
    padding: 6,
    backgroundColor: theme.colors.card,
    borderRadius: 16,
  },
  pickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  pickerIconBg: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  pickerOptionText: {
    flex: 1,
  },
  pickerOptionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text.primary,
    marginBottom: 2,
  },
  pickerOptionSub: {
    fontSize: 13,
    color: theme.colors.text.secondary,
  },
});
