import type { GradingSystem } from './grading';

export const DEFAULT_GRADING_SYSTEMS: GradingSystem[] = [
  {
    id: 1,
    code: 'COL_0_5',
    name: 'Colombia – Escala 0-5',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'CO',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 1,
    min_value: 0,
    max_value: 5,
    passing_value: 3,
    precision: 2,
  },
  {
    id: 2,
    code: 'ES_0_10',
    name: 'España – Escala 0-10',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'ES',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 2,
    min_value: 0,
    max_value: 10,
    passing_value: 5,
    precision: 2,
  },
  {
    id: 3,
    code: 'US_GPA_4',
    name: 'EE.UU. – GPA 4.0',
    type: 'gpa',
    mode: 'discrete',
    direction: 'ascending',
    country_code: 'US',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 3,
    min_value: 0,
    max_value: 4,
    passing_value: 2,
    precision: 1,
  },
  {
    id: 4,
    code: '0_100_PCT',
    name: 'Porcentaje 0-100',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'XX',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 4,
    min_value: 0,
    max_value: 100,
    passing_value: 60,
    precision: 0,
  },
  {
    id: 5,
    code: 'CL_1_7',
    name: 'Chile – Escala 1-7',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'CL',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 5,
    min_value: 1,
    max_value: 7,
    passing_value: 4,
    precision: 1,
  },
  {
    id: 6,
    code: 'MX_0_10',
    name: 'México – Escala 0-10',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'MX',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 6,
    min_value: 0,
    max_value: 10,
    passing_value: 6,
    precision: 1,
  },
  {
    id: 7,
    code: 'US_LETTER',
    name: 'EE.UU. – Letras A-F',
    type: 'letter',
    mode: 'discrete',
    direction: 'ascending',
    country_code: 'US',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 7,
    min_value: 0,
    max_value: 4.33,
    passing_value: 2.0,
    precision: 2,
  },
];
