import type { GradingSystem } from './grading';

export const DEFAULT_GRADING_SYSTEMS: GradingSystem[] = [
  {
    id: 1,
    code: 'COL_0_5',
    name: 'academic.scaleColombia',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'CO',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 1,
    min_value: 0,
    max_value: 5,
    passing_value: 3,
    precision: 2,
  },
  {
    id: 2,
    code: 'ES_0_10',
    name: 'academic.scaleSpain',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'ES',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 2,
    min_value: 0,
    max_value: 10,
    passing_value: 5,
    precision: 2,
  },
  {
    id: 3,
    code: 'US_GPA_4',
    name: 'academic.scaleUSGPA',
    type: 'gpa',
    mode: 'discrete',
    direction: 'ascending',
    country_code: 'US',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 3,
    min_value: 0,
    max_value: 4,
    passing_value: 2,
    precision: 1,
  },
  {
    id: 4,
    code: '0_100_PCT',
    name: 'academic.scalePercent',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'XX',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 4,
    min_value: 0,
    max_value: 100,
    passing_value: 60,
    precision: 0,
  },
  {
    id: 5,
    code: 'CL_1_7',
    name: 'academic.scaleChile',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'CL',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 5,
    min_value: 1,
    max_value: 7,
    passing_value: 4,
    precision: 1,
  },
  {
    id: 6,
    code: 'MX_0_10',
    name: 'academic.scaleMexico',
    type: 'numeric',
    mode: 'continuous',
    direction: 'ascending',
    country_code: 'MX',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 6,
    min_value: 0,
    max_value: 10,
    passing_value: 6,
    precision: 1,
  },
  {
    id: 7,
    code: 'US_LETTER',
    name: 'academic.scaleUSLetter',
    type: 'letter',
    mode: 'discrete',
    direction: 'ascending',
    country_code: 'US',
    is_system_seeded: true,
    is_custom: false,
    created_by_user_id: null,
    based_on_system_id: null,
    active_version_id: 7,
    min_value: 0,
    max_value: 100,
    passing_value: 60,
    precision: 0,
  },
];

import type { GradingScale } from './grading';

export const US_LETTER_SCALES: GradingScale[] = [
  { id: 0, grading_version_id: 0, label: 'A', gpa_equivalent: 4.0, min_score: 93, max_score: 100, color: '#34C759', sort_order: 1, is_passing: true, display_short_label: 'A', display_color: '#34C759', display_priority: 1 },
  { id: 0, grading_version_id: 0, label: 'A-', gpa_equivalent: 3.7, min_score: 90, max_score: 92, color: '#34C759', sort_order: 2, is_passing: true, display_short_label: 'A-', display_color: '#34C759', display_priority: 2 },
  { id: 0, grading_version_id: 0, label: 'B+', gpa_equivalent: 3.3, min_score: 87, max_score: 89, color: '#5AC8FA', sort_order: 3, is_passing: true, display_short_label: 'B+', display_color: '#5AC8FA', display_priority: 3 },
  { id: 0, grading_version_id: 0, label: 'B', gpa_equivalent: 3.0, min_score: 83, max_score: 86, color: '#5AC8FA', sort_order: 4, is_passing: true, display_short_label: 'B', display_color: '#5AC8FA', display_priority: 4 },
  { id: 0, grading_version_id: 0, label: 'B-', gpa_equivalent: 2.7, min_score: 80, max_score: 82, color: '#5AC8FA', sort_order: 5, is_passing: true, display_short_label: 'B-', display_color: '#5AC8FA', display_priority: 5 },
  { id: 0, grading_version_id: 0, label: 'C+', gpa_equivalent: 2.3, min_score: 77, max_score: 79, color: '#FF9500', sort_order: 6, is_passing: true, display_short_label: 'C+', display_color: '#FF9500', display_priority: 6 },
  { id: 0, grading_version_id: 0, label: 'C', gpa_equivalent: 2.0, min_score: 73, max_score: 76, color: '#FF9500', sort_order: 7, is_passing: true, display_short_label: 'C', display_color: '#FF9500', display_priority: 7 },
  { id: 0, grading_version_id: 0, label: 'C-', gpa_equivalent: 1.7, min_score: 70, max_score: 72, color: '#FF9500', sort_order: 8, is_passing: true, display_short_label: 'C-', display_color: '#FF9500', display_priority: 8 },
  { id: 0, grading_version_id: 0, label: 'D+', gpa_equivalent: 1.3, min_score: 67, max_score: 69, color: '#FF2D55', sort_order: 9, is_passing: true, display_short_label: 'D+', display_color: '#FF2D55', display_priority: 9 },
  { id: 0, grading_version_id: 0, label: 'D', gpa_equivalent: 1.0, min_score: 63, max_score: 66, color: '#FF2D55', sort_order: 10, is_passing: true, display_short_label: 'D', display_color: '#FF2D55', display_priority: 10 },
  { id: 0, grading_version_id: 0, label: 'D-', gpa_equivalent: 0.7, min_score: 60, max_score: 62, color: '#FF2D55', sort_order: 11, is_passing: true, display_short_label: 'D-', display_color: '#FF2D55', display_priority: 11 },
  { id: 0, grading_version_id: 0, label: 'F', gpa_equivalent: 0.0, min_score: 0, max_score: 59, color: '#8B0000', sort_order: 12, is_passing: false, display_short_label: 'F', display_color: '#8B0000', display_priority: 12 },
];
