import { RepositoryFactory } from '../database/RepositoryFactory';
import { getUserId } from '../api/auth';
import type { GeneratedCard } from '../ai/capabilities/FlashcardCapability';

export interface RichCard {
  id: string;
  deckId: string;
  front?: string;
  back?: string;
  item_type?: string;
  content_json?: string;
  hint?: string | null;
  explanation?: string | null;
  direction?: string;
  source_context?: string;
}

export interface PersistDeckParams {
  id: string;
  title: string;
  description: string;
  topic?: string | null;
  subjectId?: string | number;
  subjectName?: string;
  subjectColor?: string;
  subjectIcon?: string;
  cards: (GeneratedCard | RichCard)[];
}

export function assertDeckPersistenceContract(deck: PersistDeckParams): void {
  if (!deck?.id) {
    throw new Error(
      '[FlashcardDomainService] saveGeneratedDeck requiere deck.id. El servicio no inventa identidades: el id lo decide el backend o se genera antes de llamar al servicio.'
    );
  }

  const cards = deck.cards || [];
  for (const card of cards) {
    const c = card as any;
    if (!c.id) {
      throw new Error(
        `[FlashcardDomainService] saveGeneratedDeck requiere que cada card tenga su id (card sin id: ${JSON.stringify(c).slice(0, 120)}).`
      );
    }
    if (c.deckId !== deck.id) {
      throw new Error(
        `[FlashcardDomainService] card.deckId (${c.deckId}) no coincide con deck.id (${deck.id}).`
      );
    }
  }
}

export class FlashcardDomainService {
  /**
   * Persists a deck and its cards through the domain repositories.
   * Idempotent: INSERT if the deck does not exist, UPDATE if it does.
   * The service NEVER decides identities — deck.id and card ids come from
   * the backend (server-created deck) or are pre-generated by the caller
   * (offline flow). Titles are not renamed here either.
   */
  async saveGeneratedDeck(params: PersistDeckParams) {
    assertDeckPersistenceContract(params);

    const userId = await getUserId();
    const user = String(userId || 0);

    const existingDeck = await RepositoryFactory.flashcardDecks().getByIdIncludingDeleted(params.id);
    const deckData = {
      title: params.title,
      description: params.description,
      topic: params.topic ?? null,
      subject_id: params.subjectId ? String(params.subjectId) : undefined,
      subject_name: params.subjectName,
      subject_color: params.subjectColor,
      subject_icon: params.subjectIcon,
      card_count: params.cards.length,
      user_id: user,
    };

    if (existingDeck) {
      await RepositoryFactory.flashcardDecks().update(params.id, deckData);
    } else {
      await RepositoryFactory.flashcardDecks().create({
        id: params.id,
        ...deckData,
        created_at: new Date().toISOString(),
        review_count: 0,
        learning_count: 0,
        new_count: params.cards.length,
      });
    }

    for (const card of params.cards) {
      const c = card as any;
      const itemType = c.item_type ?? c.type ?? 'flashcard';
      const front = c.front ?? c.pregunta ?? (c.data && c.data.front) ?? '';
      const back = c.back ?? c.respuesta ?? '';
      const cardData = {
        deck_id: params.id,
        front,
        back,
        item_type: itemType,
        content_json: c.content_json ?? (c.data ? JSON.stringify(c.data) : undefined),
        hint: c.hint ?? null,
        explanation: c.explanation ?? null,
        direction: c.direction ?? undefined,
        source_context: c.source_context ?? undefined,
      };

      const existingCard = await RepositoryFactory.flashcards().getByIdIncludingDeleted(c.id);
      if (existingCard) {
        await RepositoryFactory.flashcards().update(c.id, cardData as any);
      } else {
        await RepositoryFactory.flashcards().create({ id: c.id, ...cardData } as any);
      }
    }

    return {
      id: params.id,
      title: params.title,
      description: params.description,
      subject_id: params.subjectId ? String(params.subjectId) : undefined,
      card_count: params.cards.length,
      cards: params.cards,
    };
  }
}

export const flashcardDomainService = new FlashcardDomainService();
